library:
  join: background.js
  compress: true
  files:
    - src/background_core.coffee
    - src/background_job.coffee
    - src/background_job_queue.coffee
    - src/background_job_list.coffee
    - src/background_range.coffee
    - src/background_range_xN.coffee
    - src/background_array_iterator.coffee
    - src/background_array_iterator_xN.coffee

examples:
  output: build
  directories:
    - examples

tests:
  output: build
  directories:
    - test/core
    - test/packaging
  modes:
    build:
      bundles:
        test/packaging/build/bundle.js:
          background: background.js
      no_files_ok: ['test/packaging']
    test:
      command: phantomjs
      runner: phantomjs-jasmine-runner.js
      files:
        - '**/*.html'