library:
  join: background.js
  minimize: true
  files:
    - src/background_core.coffee
    - src/background_job.coffee
    - src/background_job_queue.coffee
    - src/background_job_list.coffee
    - src/background_range.coffee
    - src/background_range_xN.coffee
    - src/background_array_iterator.coffee
    - src/background_array_iterator_xN.coffee

examples:
  output: ./build
  directories:
    - examples

tests:
  output: ./build
  directories:
    - spec
  options:
    test:
      timeout: 60000
      runner: phantomjs-jasmine-runner.js