gzip_assets: off
compress_assets: off

javascripts:
  'background':
    - build/background_core.js
    - build/background_job.js
    - build/background_job_queue.js
    - build/background_job_list.js
    - build/background_range.js
    - build/background_range_xN.js
    - build/background_array_iterator.js
    - build/background_array_iterator_xN.js