gzip_assets: off
compress_assets: on

javascripts:
  'background.min':
    - build/background_core.js
    - build/background_job.js
    - build/background_job_queue.js
    - build/background_job_list.js
    - build/background_range.js
    - build/background_array_iterator.js
