gzip_assets: off
compress_assets: on

javascripts:
  'background.min':
    - build/parts/bg_core.js
    - build/parts/bg_job.js
    - build/parts/bg_job_queue.js
    - build/parts/bg_job_list.js
    - build/parts/bg_range.js
    - build/parts/bg_array_iterator.js
